### PR TITLE
Fix protocol property being ignored in system tests

### PR DESCRIPTION
**Pull request by t1m0thyj**
**What It Does**

**How to Test**

**Review Checklist**
I certify that I have:
- [ ] tested my changes
- [ ] added/updated automated tests
- [ ] updated the changelog
- [ ] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

### CODE REVIEW

**Review by traeok — APPROVED** [review]
LGTM, thanks Timothy for the fix

**Review by gejohnston — APPROVED** [review]
Is the reason why the two 'query_queue_manager' scripts display in 'Files changed' as 'empty file' because only permissions on the files were changed?

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋 
Also, thanks for making the shell scripts executables 🥳

**Comment by t1m0thyj** [comment]
> Is the reason why the two 'query_queue_manager' scripts display in 'Files changed' as 'empty file' because only permissions on the files were changed?

@gejohnston Yes I'm not sure why the GitHub PR diff shows them as "Empty file" since that is misleading 😀 The only change was to the permissions (`644` -> `755`)

**Pull request merged**
