### PR TITLE
Delete LICENSE_HEADER

### PR DESCRIPTION
**Pull request by jmertic**
Having this file messes up GitHub's license identification - not really something that's needed so seeing if it makes sense to delete.

Signed-off-by: John Mertic <jmertic@linuxfoundation.org>

### CODE REVIEW

**Comment by zFernand0** [comment]
Hey @jmertic,
Thi sis the file used to populate the header of each source-code file on the repository by the `updateLicense.js` script.
If you notice, the pipeline failed during that step.
I'm Ok with removing it as long as it's fine to not have the short version of the license as the header of every file.

**Comment by jmertic** [comment]
Could we rename it to something else perhaps? Or maybe add it inside the scripts directory?

**Comment by zFernand0** [comment]
> Could we rename it to something else perhaps? Or maybe add it inside the scripts directory?

Oh, So the problem isn't with the filename itself, is with the location of a second `*LICENSE*` file on the root of the project.

I'm sure it can be arranged. 😄

**Comment by jmertic** [comment]
Cool - sorry for this and thanks for helping me understand.

**Pull request closed without merging**
